# Generated by Django 3.2.11 on 2022-01-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_title', models.CharField(max_length=50, null=True, verbose_name='wiki article')),
                ('target', models.CharField(max_length=50, null=True, verbose_name='target language')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Original sentence')),
                ('translated_sentence', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Translated sentence')),
                ('project_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.project', verbose_name='Project')),
            ],
        ),
    ]
